# Generated by Django 5.0.2 on 2024-02-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="expertresponse",
            name="expert_response",
            field=models.CharField(max_length=2000),
        ),
    ]
