# Generated by Django 5.0.2 on 2024-02-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_question_upvotes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertresponse",
            name="question",
        ),
        migrations.AddField(
            model_name="question",
            name="ai_response",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="question",
            name="expert_response",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.DeleteModel(
            name="AIResponse",
        ),
        migrations.DeleteModel(
            name="ExpertResponse",
        ),
    ]
